#!/bin/bash

if [[ $(git ls-files . --exclude-standard --others -m) ]]; then
	echo "Error: Push is not possible. There are unstaged or untracked files."
	exit 1
fi

./pants update-build-files lint check test --update-build-files-check :: &&
	./pants run docs/doctests.py &&
	./pants run docs/build.py
exit_code=$?

if [ $exit_code -ne 0 ]; then
	echo "Error: Push is not possible."
	exit 1
fi
