[GLOBAL]
pants_version = "2.16.0"
backend_packages = [
    "pants.backend.codegen.protobuf.lint.buf",
    "pants.backend.codegen.protobuf.python",
    "pants.backend.docker",
    "pants.backend.docker.lint.hadolint",
    "pants.backend.experimental.python",
    "pants.backend.python",
    "pants.backend.python.lint.autoflake",
    "pants.backend.python.lint.black",
    "pants.backend.python.lint.flake8",
    "pants.backend.python.lint.isort",
    "pants.backend.python.mixed_interpreter_constraints",
    "pants.backend.python.typecheck.mypy",
    "pants.backend.shell",
    "pants.backend.shell.lint.shellcheck",
    "pants.backend.shell.lint.shfmt",
]
ignore_warnings = [
    # Visit https://github.com/pantsbuild/pants/issues/19376 for more information. We
    # also added 'lockfile = "<none>"' to each Python tool to prevent using the Pants
    # internal lockfiles because it doesn't support PyPI mirrors (e.g. JFrog).
    "DEPRECATED: option 'export'",
    "DEPRECATED: option 'extra_requirements'",
    "DEPRECATED: option 'lockfile'",
    "DEPRECATED: option 'version'",
]
print_stacktrace = true
pants_ignore.add = ["!.githooks/", "!.github/", "!generated/", "!*_pb2.py", "!*.pyi", "!*_grpc.py"]

# remote_cache_read = true
# remote_cache_write = true
# remote_store_address = "grpc://localhost:9092"
# remote_instance_name = "main"

# remote_execution = true
# remote_store_address = "grpc://localhost:50051"
# remote_execution_address = "grpc://localhost:50051"
# remote_instance_name = "main"

# [environments-preview.names]
# default = "//:remote_busybox"
# local = "//:local"

[source]
root_patterns = ["/", "/src"]

[python]
interpreter_constraints = ["CPython>=3.8,<3.10"]
run_against_entire_lockfile = true
enable_resolves = true

[python.resolves]
python-default = "thirdparty/requirements.lock"

[python-infer]
unowned_dependency_behavior = "error"

[python-protobuf]
mypy_plugin = true

[flake8]
version = "flake8==5.0.4"
lockfile = "<none>"
export = false
extra_files = ["pyproject.toml"]
extra_requirements = [
    "flake8-annotations==2.9.1",
    "flake8-class-attributes-order==0.1.3",
    "flake8-docstrings==1.7.0",
    "flake8-eradicate==1.4.0",
    "flake8-mutable==1.2.0",
    "flake8-pyproject==1.2.3",
    "flake8-quotes==3.3.2",
    "flake8-simplify==0.20.0",
]

[autoflake]
lockfile = "<none>"
export = false
# The Pants' autoflake section doesn't support config file!
args = [
    "--exclude conftest.py",
    "--ignore-init-module-imports",
    "--ignore-pass-after-docstring",
]

[isort]
lockfile = "<none>"
export = false

[black]
lockfile = "<none>"
export=false

[mypy]
lockfile = "<none>"
export = false

[test]
report = true

[pytest]
lockfile = "<none>"
export = false

[coverage-py]
lockfile = "<none>"
filter = ["src"]
report = ["console", "html"]

# It is the last coverage value seen. It should be increased after each commit
# until reaching 100%.
fail_under = 48

[buf]
# Buf was used with the following configuration to apply minimal changes at the code level. During the development
# process, efforts will be made to make the structure of the existing Protobufs more consistent with the style guide of
# Buf tool so that the following exceptions are removed as much as possible.
lint_args = """
--config \"{
    'version': 'v1',
    'lint': {
        'except': [
            'PACKAGE_DIRECTORY_MATCH',
            'PACKAGE_VERSION_SUFFIX',
            'PACKAGE_DEFINED',
            'PACKAGE_SAME_DIRECTORY',
        ]
    }
}\""""

[twine]
lockfile = "<none>"

[setuptools-scm]
lockfile = "<none>"

[subprocess-environment]
env_vars.add = [
    "HTTP_PROXY",
    "HTTPS_PROXY"
]

[anonymous-telemetry]
enabled = false
