[tool.pytest.ini_options]
testpaths = ["tests"]
markers = ["smoke"]
addopts = "--import-mode=importlib"
pythonpath = [".", "src"]
filterwarnings = "ignore::DeprecationWarning:^(?!fitzy).*$"

[tool.flake8]
per-file-ignores = [
    "__init__.py:F401",
    "conftest.py:F401,F403,E501"
]
extend-ignore = [
    "D100", "D101", "D102", "D103", "D104", "D105", "D106", "D107", "D200", "D202", "D301",
    "ANN101", "ANN102",
    "SIM117",
    "Q003",
    "E800",
    "CCE001"
]
inline-quotes = "double"
eradicate-whitelist-extend = "isort.*"
max-line-length = 120

[tool.mypy]
namespace_packages = true
explicit_package_bases = true

no_implicit_optional = true
strict_equality = true
implicit_reexport = false

warn_unused_configs = true
warn_unused_ignores = true
warn_return_any = true
warn_redundant_casts = true
warn_unreachable = true
check_untyped_defs = true

pretty = true
show_column_numbers = true
show_error_context = true
show_error_codes = true
show_traceback = true

[[tool.mypy.overrides]]
# This list should be checked periodically. Maybe, one of them becomes
# type-safe.
module = []
ignore_missing_imports = true

[tool.black]
preview = true
line_length = 88

[tool.isort]
profile = "black"
line_length = 88
