---
name: Deploy and run the acceptance tests

on:
  workflow_dispatch:
    inputs:
      reference:
        description: "The reference (commit, branch, tag) which this workflow runs on."
        required: false
        type: number

jobs:
  deploy-and-test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          ref: {{ github.event.inputs.reference }}
      - run: "echo {{ github.ref_name }}"
      # - run: "docker compose up -d"
      # - uses: actions/setup-python@v4
      #   with:
      #     python-version: "3.9"
      # - run: "./pants --filter-target-type=docker_image package ::"
      # - run: "./pants test tests/acceptance:: -- -m 'not smoke'"
      # - run: "docker compose down"
      # - uses: actions/upload-artifact@v3
      #   with:
      #     name: test-reports
      #     path: |
      #       dist/coverage/
      #       dist/test/
