---
name: Release the application

on: [workflow_dispatch]

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - run: echo "Download the binaries"
      - run: echo "Deploy the application"
      - run: echo "Run the deployment tests"
